//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string RIGHTJET = "rightjet";
        
        public const string LEFTSPIN = "leftspin";
        
        public const string FRONT = "front";
        
        public const string ESTABILIZADOR = "estabilizador";
        
        public const string GAME_START = "game_start";
        
        public const string LEFTJET = "leftjet";
        
        public const string DOWNJETPACK = "downjetpack";
        
        public const string RIGHTSPIN = "rightspin";
        
        public const string PANEOARRIBA = "paneoarriba";
        
        public const string PANEOABAJO = "paneoabajo";
        
        public const string UPJETPACK = "upjetpack";
        
        public const string BACKJET = "backjet";
    }
}
